#' Get raw CHIRTS raster data
#'
#' Download CHIRTS daily temperature and humidity data in its original raster
#' format.
#'
#' This function returns CHIRTS raster layers as a
#' \code{\link[terra]{SpatRaster}} without extracting values, reshaping the data,
#' or converting it to a data frame.
#'
#' @param dates Character vector of length two with start and end dates in
#'   \code{"YYYY-MM-DD"} format.
#' @param var Character. CHIRTS variable. Supported values are
#'   \code{"Tmax"}, \code{"Tmin"}, \code{"RHum"}, and \code{"HeatIndex"}.
#' @param resolution Numeric. Spatial resolution. Default is \code{0.05}.
#' @param coverage Character. Spatial coverage. Default is \code{"global"}.
#' @param interval Character. Temporal interval. Default is \code{"daily"}.
#'   Currently retained for API consistency.
#' @param format Character. File format folder. Default is \code{"tifs"}.
#' @param version Character or numeric. CHIRTS version. Default is \code{"1.0"}.
#' @param use_vsicurl Logical. If \code{TRUE}, prepends \code{"/vsicurl"} to
#'   remote URLs.
#' @param verbose Logical. If \code{TRUE}, prints the URLs used.
#' @param ... Additional arguments reserved for future use.
#' @return A \code{\link[terra]{SpatRaster}} with one layer per day.
#' 
#' @details
#' CHIRTS-daily (Climate Hazards Center Infrared Temperature with Stations)
#' is a quasi-global (60°S to 70°N), high-resolution (0.05° × 0.05°)
#' dataset of daily maximum and minimum temperatures covering 1983–2016.
#'
#' CHIRTS-daily combines monthly CHIRTS temperature fields with daily
#' temperature variability from the ERA5 reanalysis to produce a spatially
#' detailed and temporally consistent temperature record suitable for
#' monitoring climate variability and temperature extremes.
#'
#' Daily maximum temperatures are generated by combining monthly CHIRTS
#' temperature estimates with daily ERA5 anomalies. Daily minimum
#' temperatures are subsequently derived using the ERA5 diurnal
#' temperature range.
#'
#' Additional information is available at:
#' \url{https://www.chc.ucsb.edu/data/chirtsdaily}
#' 
#' @references
#' Verdin, A., Funk, C., Peterson, P., Landsfeld, M.,
#' Tuholske, C., and Grace, K. (2020).
#' Development and validation of the CHIRTS-daily quasi-global
#' high-resolution daily temperature data set.
#' Scientific Data, 7, 303.
#' \doi{10.1038/s41597-020-00643-7}
#'
#' Funk, C., Peterson, P., Peterson, S., Shukla, S.,
#' Davenport, F., Michaelsen, J., et al. (2019).
#' A High-Resolution 1983–2016 Tmax Climate Data Record Based on
#' Infrared Temperatures and Stations by the Climate Hazards Center.
#' Journal of Climate, 32, 5639–5658.
#' \doi{10.1175/JCLI-D-18-0698.1}
#' 
#' @note
#' CHIRTS-daily provides historical daily temperature estimates for
#' 1983–2016. For an extended record from 1980 to near-present,
#' see \code{\link{get_chirts_era5_raw}}.
#' 
#' @examples
#' #' if (interactive()) {
#'   r = get_chirts_raw(dates = c("2015-01-01", "2015-01-31"),
#'                      var = "Tmax")
#' }
#'
#' @importFrom terra rast time<-
#' @export
get_chirts_raw = function(dates,
                          var,
                          resolution = 0.05,
                          coverage = "global",
                          interval = "daily",
                          format = "tifs",
                          version = "1.0",
                          use_vsicurl = FALSE,
                          verbose = FALSE,
                          ...) {
  
  .validate_dates(dates)
  
  var = match.arg(var, c("HeatIndex", "RHum", "Tmax", "Tmin"))
  
  version = as.character(version)
  if (version == "1") {
    version = "1.0"
  }
  
  if (!version %in% "1.0") {
    stop("`version` must be '1.0'.", call. = FALSE)
  }
  
  seqdate = seq.Date(as.Date(dates[1]), as.Date(dates[2]), by = "day")
  
  urls = .chirts_raw_urls(
    dates = seqdate,
    var = var,
    resolution = resolution,
    coverage = coverage,
    interval = interval,
    format = format,
    version = version
  )
  
  if (isTRUE(use_vsicurl)) {
    urls = file.path("/vsicurl", urls)
  }
  
  if (isTRUE(verbose)) {
    message(paste(urls, collapse = "\n"))
  }
  
  r = terra::rast(urls)
  terra::time(r) = seqdate
  
  r
}

#' @noRd
.chirts_raw_urls = function(dates,
                            var,
                            resolution = 0.05,
                            coverage = "global",
                            interval = "daily",
                            format = "tifs",
                            version = "1.0") {
  
  years = format(dates, "%Y")
  year_int = as.integer(years)
  
  if (any(!year_int %in% 1983:2016)) {
    stop("CHIRTS data are only available from 1983 to 2016.",
         call. = FALSE)
  }
  
  if (!resolution %in% c(0.05)) {
    stop("For CHIRTS v1.0, only `resolution = 0.05` is currently supported.",
         call. = FALSE)
  }
  
  if (!identical(coverage, "global")) {
    stop("For CHIRTS v1.0, only `coverage = 'global'` is currently supported.",
         call. = FALSE)
  }
  
  if (!identical(format, "tifs")) {
    stop("For CHIRTS v1.0, only `format = 'tifs'` is currently supported.",
         call. = FALSE)
  }
  
  file_var = var
  if (identical(var, "RHum")) {
    file_var = "RH"
  }
  
  date_string = gsub("-", ".", dates)
  
  fnames = file.path(
    years,
    paste0(file_var, ".", date_string, ".tif")
  )
  
  resolution = gsub("0\\.", "p", as.character(resolution))
  
  file.path(
    "https://data.chc.ucsb.edu/products/CHIRTSdaily/v1.0",
    paste0(coverage, "_", format, "_", resolution),
    var,
    fnames
  )
}


